src/Mindee/Parsing/MindeeApi.cs
… handle reused authentication header
=> :bug: prevent auto redirection from RestSharp dep because it does not reuse authentication header

docs/code_samples/us_driver_license_v1.txt, src/Mindee/Product/Us/DriverLicense/DriverLicenseV1.cs, src/Mindee/Product/Us/DriverLicense/DriverLicenseV1Document.cs, src/Mindee/Product/Us/DriverLicense/DriverLicenseV1Page.cs, tests/Mindee.UnitTests/Product/FinancialDocument/FinancialDocumentV1Test.cs, tests/Mindee.UnitTests/Product/Us/DriverLicense/DriverLicenseV1Test.cs
=> :sprakles: add us driver license v1

CHANGELOG.md, Directory.Build.props
* :sparkles: add support for FR ID card v2
* :sparkles: add support for US W9 v1
* :sparkles: add built-in async call polling
* :sparkles: add DecimalField
* :loud_sound: better logging
* :sparkles: add a dateObject property to DateField class
* :bug: fix for alignment issues on ToString
* :bug: StringField value should be null in case of empty string
=> :bookmark: version 3.2.0

src/Mindee/Product/Invoice/InvoiceV4Document.cs, tests/Mindee.UnitTests/Product/Invoice/InvoiceV4Test.cs
:sparkles: update Invoice to v4.5
=> :sparkles: update Invoice to v4.5

.github/workflows/integration-tests.yml, .github/workflows/test-sample-codes.yml, .github/workflows/unit-tests.yml, README.md, src/Mindee/Input/PageOptions.cs, src/Mindee/MindeeClient.cs, src/Mindee/Pdf/SplitQuery.cs, tests/Mindee.UnitTests/MindeeClientTest.cs, tests/Mindee.UnitTests/Pdf/PdfOperationTest.cs
* Add a test for cutting a PDF in the client.
* Hard-code OS versions to avoid problems when  GH decides to change things (macos-14 has no PDF support).
* Make sure we always install dotnet 6.0 when GH decides to change things.
=> :white_check_mark: add unit test for PageOptions

src/Mindee/Product/FinancialDocument/FinancialDocumentV1Document.cs, src/Mindee/Product/Receipt/ReceiptV5Document.cs, tests/Mindee.UnitTests/Product/Receipt/ReceiptV5Test.cs
* :sparkles: update receipt API to v5.2
* :sparkles: update financial doc API to 1.7
* :recycle: update test lib
=> :sparkles: update financial document to 1.7 & receipt to 5.2

.github/PULL_REQUEST_TEMPLATE.md, docs/code_samples/us_mail_v2_async.txt, src/Mindee/Parsing/Custom/LineItem/LineItemsGenerator.cs, src/Mindee/Parsing/Standard/BooleanField.cs, src/Mindee/Parsing/SummaryHelper.cs, src/Mindee/Product/Us/UsMail/UsMailV2.cs, src/Mindee/Product/Us/UsMail/UsMailV2Document.cs, src/Mindee/Product/Us/UsMail/UsMailV2RecipientAddress.cs, src/Mindee/Product/Us/UsMail/UsMailV2SenderAddres.cs, tests/Mindee.UnitTests/Product/Us/UsMail/UsMailV2Test.cs
* add support for Boolean fields
* add new product US Mail
=> :sparkles: add support for US Mail

src/Mindee.Cli/Commands/OutputType.cs, src/Mindee.Cli/Commands/PredictCommand.cs, src/Mindee.Cli/Commands/PredictCustomCommand.cs, src/Mindee/Geometry/Utils.cs, src/Mindee/Parsing/Common/AsyncPredictResponse.cs, src/Mindee/Parsing/Common/Ocr.cs, tests/Mindee.UnitTests/Parsing/Common/OcrTest.cs
Finally add support for raw OCR to string, as requested by a user.
=> :sparkles: add support for getting the raw OCR as a string

src/Mindee/Parsing/Standard/CompanyRegistration.cs
* :recycle: add type on company registration print
=> :recycle: update company registration display

src/Mindee/Http/MindeeApi.cs, src/Mindee/Mindee.csproj
Fix issue addressed in #219
* :recycle: refactor to accommodate for update
=> :arrow_up: update RestSharp & System.Text.json

CHANGELOG.md, Directory.Build.props
=> :bookmark: Version 3.17.0

.github/workflows/integration-tests.yml, .github/workflows/test-sample-codes.yml, sample/Mindee.Sample.Net472/Mindee.Sample.Net472.csproj, sample/Mindee.Sample.Net472/packages.config, sample/Mindee.Sample.Net48/Mindee.Sample.Net48.csproj, sample/Mindee.Sample.Net48/packages.config, src/Mindee/Http/MindeeApi.cs, src/Mindee/Mindee.csproj, src/Mindee/MindeeSettings.cs, tests/Mindee.IntegrationTests/Extraction/InvoiceSplitterAutoExtractionTest.cs, tests/Mindee.IntegrationTests/MindeeClientTest.cs
Refuses to compile:
> error NU1903: Warning As Error: Package 'System.Text.Json' 8.0.3 has a known high severity vulnerability, https://github.com/advisories/GHSA-hh2w-p6rv-4g7w
=> :arrow_up: update System.Text.Json for vulnerability fix

src/Mindee.Cli/Program.cs
=> :sparkles: add us-mail to CLI

src/Mindee/Extraction/PdfExtractor.cs, tests/Mindee.UnitTests/Extraction/PdfExtractorTest.cs, tests/Mindee.UnitTests/Input/LocalInputSourceTest.cs
* :bug: fix pdfextractor breaking when an image was loaded
* :recycle: add unit test for memory stream loading
=> :bug: fix invalid loading of images into pdf extractor

.github/workflows/integration-tests.yml, src/Mindee.Cli/Mindee.Cli.csproj, src/Mindee/DependencyInjection/ServiceCollectionExtensions.cs, src/Mindee/Http/MindeeApi.cs, src/Mindee/Mindee.csproj, src/Mindee/MindeeClient.cs, tests/Mindee.IntegrationTests/Extraction/InvoiceSplitterAutoExtractionTest.cs, tests/Mindee.IntegrationTests/Mindee.IntegrationTests.csproj, tests/Mindee.IntegrationTests/MindeeClientTest.cs, tests/Mindee.IntegrationTests/TestingUtilities.cs, tests/Mindee.UnitTests/Extraction/PdfExtractorTest.cs, tests/Mindee.UnitTests/Http/MindeeApiTest.cs, tests/Mindee.UnitTests/Mindee.UnitTests.csproj, tests/Mindee.UnitTests/UnitTestBase.cs
* Switch restsharp client initialization to singleton
* Use basic dependency injections to prevent hanging connections
* Add hard-coded security protocol to prevent timeouts in version 4.7.2
* Switch mocking systems
=> :bug: fix integration testing crashing

CHANGELOG.md, Directory.Build.props
=> :bookmark: Version 3.18.0

CHANGELOG.md, Directory.Build.props
=> :bookmark: Version 3.18.1

src/Mindee/ServiceCollectionsExtensions.cs
Upgrade scope of resclient to allow workers to access restclient
=> :bug: fix restclient being given improper scope for worker access

CHANGELOG.md, Directory.Build.props
=> :bookmark: Version 3.18.2

src/Mindee/ServiceCollectionsExtensions.cs, tests/Mindee.IntegrationTests/DependencyInjectionTest.cs, tests/Mindee.IntegrationTests/Mindee.IntegrationTests.csproj
* :recycle: force full creation of RestSharp RestClient instance on worker service call
* :recycle: add relevant test
* :recycle: update dependencies
=> :bug: fix broken reference on worker service initialization

CHANGELOG.md, Directory.Build.props
=> :bookmark: Version 3.18.3

.github/workflows/integration-tests.yml, tests/Mindee.IntegrationTests/DependencyInjectionTest.cs, tests/Mindee.IntegrationTests/Mindee.IntegrationTests.csproj, tests/Mindee.IntegrationTests/TestingUtilities.cs, tests/Mindee.IntegrationTests/xunit.runner.json
=> :recycle: fix integration tests crashing

README.md, docs/idcard_fr_v2.md
=> :memo: update README & idcard_fr_v2 slug

README.md, docs/custom_v1.md
=> :memo: fix broken documentation URLs

src/Mindee/Extraction/PdfExtractor.cs, src/Mindee/Mindee.csproj, tests/Mindee.UnitTests/Extraction/PdfExtractorTest.cs
=> :recycle: bump restsharp dependency & cleanup code

CHANGELOG.md, Directory.Build.props
=> :bookmark: version 3.18.4

CHANGELOG.md, Directory.Build.props
=> :bookmark: Version 3.19.0

example/AutoInvoiceSpliterExtractionExample.cs, example/AutoMultiReceiptsExtractionExample.cs, src/Mindee/Input/LocalInputSource.cs, tests/Mindee.IntegrationTests/Extraction/InvoiceSplitterAutoExtractionTest.cs, tests/Mindee.IntegrationTests/TestingUtilities.cs, tests/Mindee.UnitTests/MindeeClientTest.cs
=> :recycle: update example scripts, test lib & tests

.github/workflows/integration-tests.yml, example/AutoInvoiceSpliterExtractionExample.cs, example/AutoMultiReceiptsExtractionExample.cs, tests/Mindee.IntegrationTests/Mindee.IntegrationTests.csproj, tests/Mindee.UnitTests/Mindee.UnitTests.csproj, tests/Mindee.UnitTests/Parsing/Common/OcrTest.cs
=> :arrow_up: update xunit dependency

src/Mindee/Extraction/ImageExtractor.cs, src/Mindee/Image/ImageCompressor.cs, src/Mindee/Image/ImageUtils.cs, src/Mindee/Pdf/PdfCompressor.cs
Rename MindeeImageUtils to ImageUtils
=> :recycle: rename image utility class to better fit existing syntax

src/Mindee/Input/LocalInputSource.cs, src/Mindee/Pdf/PdfCompressor.cs, src/Mindee/Pdf/PdfUtils.cs, tests/Mindee.UnitTests/Input/LocalInputSourceTest.cs
* :recycle: create pdf utils submodule
* :recycle: fix typos & add docstrings
=> :recycle: refactor pdf compression module

docs/bill_of_lading_v1.md, docs/energy_bill_fra_v1.md, docs/expense_receipts_v5.md, docs/financial_document_v1.md, docs/invoices_v4.md, docs/nutrition_facts_v1.md, docs/payslip_fra_v2.md, docs/us_mail_v2.md, src/Mindee/Parsing/Generated/GeneratedObject.cs, src/Mindee/Parsing/Standard/DateField.cs, src/Mindee/Product/FinancialDocument/FinancialDocumentV1Document.cs, src/Mindee/Product/Invoice/InvoiceV4Document.cs, tests/Mindee.UnitTests/Parsing/Standard/DateFieldTest.cs, tests/Mindee.UnitTests/Product/Invoice/InvoiceV4Test.cs
=> :sparkles: add support for financial document v1.10 & invoice v4.8

CHANGELOG.md, Directory.Build.props
=> :bookmark: Version 3.20.0

src/Mindee/ServiceCollectionsExtensions.cs, tests/Mindee.IntegrationTests/DependencyInjectionTest.cs
* :recycle: Switch to singleton-only syntax in DI to prevent settings from being overwritten
=> :bug: fix worker services losing API settings & API key after an HTTP call

docs/business_card_v1.md, docs/code_samples/business_card_v1_async.txt, docs/code_samples/delivery_notes_v1_async.txt, docs/code_samples/ind_passport_v1_async.txt, docs/delivery_notes_v1.md, docs/financial_document_v1.md, docs/ind_passport_v1.md, docs/invoices_v4.md, docs/resume_v1.md, src/Mindee/MindeeClientOptions.cs, src/Mindee/Product/BusinessCard/BusinessCardV1.cs, src/Mindee/Product/BusinessCard/BusinessCardV1Document.cs, src/Mindee/Product/DeliveryNote/DeliveryNoteV1.cs, src/Mindee/Product/DeliveryNote/DeliveryNoteV1Document.cs, src/Mindee/Product/FinancialDocument/FinancialDocumentV1Document.cs, src/Mindee/Product/Ind/IndianPassport/IndianPassportV1.cs, src/Mindee/Product/Ind/IndianPassport/IndianPassportV1Document.cs, src/Mindee/Product/Invoice/InvoiceV4Document.cs, src/Mindee/Product/Resume/ResumeV1Document.cs, src/Mindee/Product/Resume/ResumeV1ProfessionalExperience.cs, tests/Mindee.UnitTests/MindeeClientOptionsTest.cs, tests/Mindee.UnitTests/Product/BusinessCard/BusinessCardV1Test.cs, tests/Mindee.UnitTests/Product/DeliveryNote/DeliveryNoteV1Test.cs, tests/Mindee.UnitTests/Product/Ind/IndianPassport/IndianPassportV1Test.cs
* :sparkles: add support for business cards V1
* :sparkles: add support for delivery note V1.1
* :sparkles: add support for indian passport V1
* :sparkles: add support for resume V1.1
* :recycle: adjust default values for async delays
=> :sparkles: add support for business cards, delivery notes, indian passport & update resume

CHANGELOG.md, Directory.Build.props
=> :bookmark: Version 3.21.0

CHANGELOG.md, Directory.Build.props
=> :bookmark: Version 3.22.0

CHANGELOG.md, Directory.Build.props, README.md, docs/getting_started.md
=> :bookmark: Version 3.23.0

.github/workflows/publish-docs.yml, .github/workflows/publish-nuget.yml
=> :recycle: publish on net8.0

src/Mindee/Parsing/Generated/GeneratedFeature.cs, src/Mindee/Parsing/Generated/GeneratedObject.cs, tests/Mindee.UnitTests/Product/Generated/GeneratedV1Test.cs
* :bug: add missing boolean field accessor to generated objects
=> :bug: fix missing boolean accessor for generated object

CHANGELOG.md, Directory.Build.props
=> :bookmark: Version 3.24.1

src/Mindee/Parsing/Standard/ClassificationField.cs, tests/Mindee.UnitTests/Product/FinancialDocument/FinancialDocumentV1Test.cs
Add missing confidence score to classification fields.
=> :bug: fix classifications not having a confidence score

CHANGELOG.md, Directory.Build.props
=> :bookmark: Version 3.24.2

src/Mindee.Cli/Commands/PredictCustomCommand.cs
=> :sparkles: allow asynchronous custom products in CLI

docs/expense_receipts_v5.md, docs/financial_document_v1.md, docs/idcard_fr_v2.md, docs/ind_passport_v1.md, docs/international_id_v2.md, docs/invoice_splitter_v1.md, docs/invoices_v4.md, docs/resume_v1.md, src/Mindee.Cli/Program.cs, src/Mindee/Product/DeliveryNote/DeliveryNoteV1Document.cs, src/Mindee/Product/FinancialDocument/FinancialDocumentV1Document.cs, src/Mindee/Product/FinancialDocument/FinancialDocumentV1LineItem.cs, src/Mindee/Product/Invoice/InvoiceV4Document.cs, src/Mindee/Product/Invoice/InvoiceV4LineItem.cs, src/Mindee/Product/Receipt/ReceiptV5Document.cs, src/Mindee/Product/Receipt/ReceiptV5LineItem.cs
=> :recycle: upgrade descriptions, documentation & CLI products

docs/energy_bill_fra_v1.md, src/Mindee/Product/Fr/EnergyBill/EnergyBillV1Document.cs, src/Mindee/Product/Fr/EnergyBill/EnergyBillV1EnergyUsage.cs, src/Mindee/Product/Fr/EnergyBill/EnergyBillV1MeterDetail.cs, src/Mindee/Product/Us/HealthcareCard/HealthcareCardV1Document.cs
=> :sparkles: bump FR EnergyBillV1 to V1.2 & US HealthcareCardV1 to V1.1

CHANGELOG.md, Directory.Build.props
=> :bookmark: Version 3.25.0

CHANGELOG.md, Directory.Build.props
=> :bookmark: Version 3.26.0

.github/workflows/_codeql.yml, .github/workflows/_test-integrations.yml, docs/code_samples/workflow_polling.txt, src/Mindee/Http/MindeeApi.cs, src/Mindee/ServiceCollectionsExtensions.cs, tests/Mindee.IntegrationTests/Workflow/WorkflowTest.cs
=> :white_check_mark: add more workflow tests

docs/financial_document_v1.md, docs/invoices_v4.md, src/Mindee/Parsing/Standard/AddressField.cs, src/Mindee/Product/FinancialDocument/FinancialDocumentV1Document.cs, src/Mindee/Product/Invoice/InvoiceV4Document.cs, tests/Mindee.UnitTests/Product/FinancialDocument/FinancialDocumentV1Test.cs
=> :sparkles: add support for full address fields + upgrade products

CHANGELOG.md, Directory.Build.props
=> :bookmark: Version 3.28.0

src/Mindee/MindeeClient.cs, tests/Mindee.IntegrationTests/MindeeClientTest.cs
=> :sparkles: add support for URL input source async polling

docs/code_samples/default_v2.txt, src/Mindee/Http/GenericParameter.cs, src/Mindee/Http/PredictParameter.cs, src/Mindee/Http/PredictParameterV2.cs, src/Mindee/InferenceOptionsV2.cs, src/Mindee/InferencePredictOptions.cs, src/Mindee/MindeeClientOptions.cs, src/Mindee/MindeeClientV2.cs, src/Mindee/Parsing/V2/BaseField.cs, src/Mindee/Parsing/V2/CommonResponse.cs, src/Mindee/Parsing/V2/Job.cs, tests/Mindee.IntegrationTests/MindeeClientV2Test.cs, tests/Mindee.UnitTests/MindeeClientV2Test.cs
=> :recycle: [V2] remove redundant  & unneeded logic + fix typos

CHANGELOG.md, Directory.Build.props, src/Mindee/Parsing/V2/ObjectField.cs
=> :bookmark: Version 3.29.0-rc3

src/Mindee/Mindee.csproj, src/Mindee/Parsing/V2/Field/InferenceFields.cs, src/Mindee/Parsing/V2/Field/ListField.cs, src/Mindee/Parsing/V2/Field/ObjectField.cs, src/Mindee/Parsing/V2/Field/SimpleField.cs, src/Mindee/Parsing/V2/Field/SimpleFieldJsonConverter.cs, src/Mindee/Parsing/V2/Inference.cs, src/Mindee/Parsing/V2/InferenceResult.cs, src/Mindee/Parsing/V2/InferenceResultFile.cs, src/Mindee/Parsing/V2/InferenceResultModel.cs, tests/Mindee.IntegrationTests/Mindee.IntegrationTests.csproj, tests/Mindee.UnitTests/Mindee.UnitTests.csproj, tests/Mindee.UnitTests/Parsing/V2/InferenceV2Test.cs
* :bug: fix invalid display for some fields
* :recycle: update tests
* :bug: fix dynamic type missing dependency for .NET versions 6 and below
=> :recycle: harmonize field displays with other SDKs

CHANGELOG.md, Directory.Build.props, README.md
=> :bookmark: Version 3.29.0

src/Mindee/Input/PageOptions.cs, tests/Mindee.UnitTests/Parsing/V2/InferenceV2Test.cs
Fix page options documentation.
Add some unit tests for inference results.
=> :memo: fix page options doc, add some inference tests

src/Mindee/Parsing/V2/Field/ListField.cs, src/Mindee/Parsing/V2/Field/ObjectField.cs, tests/Mindee.UnitTests/Parsing/V2/InferenceV2Test.cs
Make it easier to access typed lists and sub-fields
=> :sparkles: add typed properties to list and object

src/Mindee/Geometry/Point.cs, src/Mindee/Parsing/Standard/DecimalJsonConverter.cs, src/Mindee/Product/Us/PayrollCheckRegister/PayrollCheckRegisterV1Deduction.cs
Fixes for decimal string output and input
=> :bug: ensure decimals are formatted properly
